# Generated by Django 4.2.1 on 2023-06-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claves', '0004_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_link', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'photos',
                'managed': True,
            },
        ),
    ]
