# Generated by Django 4.2.1 on 2023-05-24 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claves', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='item',
        ),
    ]
